// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxgtsTIkcIdXnYagY9JUQe9CbO9pAHATw',
    appId: '1:98586432516:web:01ec33ade677305f489151',
    messagingSenderId: '98586432516',
    projectId: 'authuser-5382d',
    authDomain: 'authuser-5382d.firebaseapp.com',
    storageBucket: 'authuser-5382d.firebasestorage.app',
    measurementId: 'G-6PHCCVKES3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQlJyYwdjxSAqTcyAqAxP30lYMvxEGEe8',
    appId: '1:98586432516:android:61d1813ff41e446f489151',
    messagingSenderId: '98586432516',
    projectId: 'authuser-5382d',
    storageBucket: 'authuser-5382d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi2P9dDFQevBpnakF4J_k7ttldbtLH9_s',
    appId: '1:98586432516:ios:79878652e8eafc41489151',
    messagingSenderId: '98586432516',
    projectId: 'authuser-5382d',
    storageBucket: 'authuser-5382d.firebasestorage.app',
    iosBundleId: 'com.example.excm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi2P9dDFQevBpnakF4J_k7ttldbtLH9_s',
    appId: '1:98586432516:ios:79878652e8eafc41489151',
    messagingSenderId: '98586432516',
    projectId: 'authuser-5382d',
    storageBucket: 'authuser-5382d.firebasestorage.app',
    iosBundleId: 'com.example.excm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxgtsTIkcIdXnYagY9JUQe9CbO9pAHATw',
    appId: '1:98586432516:web:401ffb7af1b5460e489151',
    messagingSenderId: '98586432516',
    projectId: 'authuser-5382d',
    authDomain: 'authuser-5382d.firebaseapp.com',
    storageBucket: 'authuser-5382d.firebasestorage.app',
    measurementId: 'G-HP2GPSB857',
  );
}
